export const currencies = [
    { code: "USD", name: "US Dollar" },
    { code: "EUR", name: "Euro" },
    { code: "GBP", name: "British Pound Sterling" },
    { code: "JPY", name: "Japanese Yen" },
    { code: "CAD", name: "Canadian Dollar" },
    { code: "AUD", name: "Australian Dollar" },
    { code: "CHF", name: "Swiss Franc" },
    { code: "CNY", name: "Chinese Yuan" },
    { code: "SEK", name: "Swedish Krona" },
    { code: "NZD", name: "New Zealand Dollar" },
    { code: "MXN", name: "Mexican Peso" },
    { code: "SGD", name: "Singapore Dollar" },
    { code: "HKD", name: "Hong Kong Dollar" },
    { code: "NOK", name: "Norwegian Krone" },
    { code: "TRY", name: "Turkish Lira" },
    { code: "RUB", name: "Russian Ruble" },
    { code: "INR", name: "Indian Rupee" },
    { code: "BRL", name: "Brazilian Real" },
    { code: "ZAR", name: "South African Rand" },
    { code: "KRW", name: "South Korean Won" },
    { code: "DZD", name: "Algerian Dinar" },
    { code: "AOA", name: "Angolan Kwanza" },
    { code: "XOF", name: "West African CFA Franc" },
    { code: "BWP", name: "Botswana Pula" },
    { code: "BIF", name: "Burundian Franc" },
    { code: "XAF", name: "Central African CFA Franc" },
    { code: "CVE", name: "Cape Verdean Escudo" },
    { code: "KMF", name: "Comorian Franc" },
    { code: "CDF", name: "Congolese Franc" },
    { code: "DJF", name: "Djiboutian Franc" },
    { code: "EGP", name: "Egyptian Pound" },
    { code: "ERN", name: "Eritrean Nakfa" },
    { code: "ETB", name: "Ethiopian Birr" },
    { code: "GMD", name: "Gambian Dalasi" },
    { code: "GHS", name: "Ghanaian Cedi" },
    { code: "GNF", name: "Guinean Franc" },
    { code: "KES", name: "Kenyan Shilling" },
    { code: "LSL", name: "Lesotho Loti" },
    { code: "LRD", name: "Liberian Dollar" },
    { code: "LYD", name: "Libyan Dinar" },
    { code: "MGA", name: "Malagasy Ariary" },
    { code: "MWK", name: "Malawian Kwacha" },
    { code: "MUR", name: "Mauritian Rupee" },
    { code: "MAD", name: "Moroccan Dirham" },
    { code: "MZN", name: "Mozambican Metical" },
    { code: "NAD", name: "Namibian Dollar" },
    { code: "NGN", name: "Nigerian Naira" },
    { code: "RWF", name: "Rwandan Franc" },
    { code: "STN", name: "São Tomé and Príncipe Dobra" },
    { code: "SCR", name: "Seychellois Rupee" },
    { code: "SLE", name: "Sierra Leonean Leone" },
    { code: "SOS", name: "Somali Shilling" },
    { code: "SSP", name: "South Sudanese Pound" },
    { code: "SDG", name: "Sudanese Pound" },
    { code: "SZL", name: "Swazi Lilangeni" },
    { code: "TZS", name: "Tanzanian Shilling" },
    { code: "TND", name: "Tunisian Dinar" },
    { code: "UGX", name: "Ugandan Shilling" },
    { code: "ZMW", name: "Zambian Kwacha" },
    { code: "ZWL", name: "Zimbabwean Dollar" },
    { code: "ARS", name: "Argentine Peso" },
    { code: "CLP", name: "Chilean Peso" },
    { code: "COP", name: "Colombian Peso" },
    { code: "PEN", name: "Peruvian Sol" },
];
